export const API_ENDPOINTS = {
  LOGIN: "/v1/auth/login",
  VOUCHERS: "/v1/vouchers",
  VOUCHER_PURCHASE: "/v1/vouchers/purchase",
  VOUCHER_SALES: "/v1/vouchers/sales",
  VOUCHER_CONVERSION: "/v1/vouchers/conversion",
  VOUCHER_RECEIPT: "/v1/vouchers/receipt",
  VOUCHER_UPDATE: (id: string) => `/v1/vouchers/${id}`,
  VOUCHER_BOOK: (id: string) => `/v1/vouchers/${id}/book`,
  VOUCHER_PAY: (id: string) => `/v1/vouchers/${id}/pay`,
  VOUCHER_PDF: (id: string) => `/v1/vouchers/${id}/pdf`,
  AUDIT_LOGS: "/v1/audit-logs",
  AR_LEDGER: "/v1/ar-ledger",
  STOCK_CARD: "/v1/reports/stock-card",
  STOCK_CARD_EXCEL: "/v1/reports/stock-card/excel",
  PARTNER_DEBT_PDF: (partnerId: string) => `/v1/partners/${partnerId}/debt-pdf`,
  PRODUCTS: "/v1/products",
  PARTNERS: "/v1/partners",
  PARTNER_BY_ID: (id: string) => `/v1/partners/${id}`,
  USERS: "/v1/users",
  USER_BY_ID: (id: string) => `/v1/users/${id}`,
  USER_RESET_PASSWORD: (id: string) => `/v1/users/${id}/reset-password`,
  SYSTEM_SETTINGS: "/v1/system-settings"
} as const;
