export const API_ENDPOINTS = {
  LOGIN: "/v1/auth/login",
  VOUCHERS: "/v1/vouchers",
  VOUCHER_PURCHASE: "/v1/vouchers/purchase",
  VOUCHER_SALES: "/v1/vouchers/sales",
  VOUCHER_SALES_RETURN: "/v1/vouchers/sales-return",
  VOUCHER_CONVERSION: "/v1/vouchers/conversion",
  VOUCHER_RECEIPT: "/v1/vouchers/receipt",
  VOUCHER_BY_ID: (id: string) => `/v1/vouchers/${id}`,
  VOUCHER_UPDATE: (id: string) => `/v1/vouchers/${id}`,
  VOUCHER_BOOK: (id: string) => `/v1/vouchers/${id}/book`,
  VOUCHER_PAY: (id: string) => `/v1/vouchers/${id}/pay`,
  VOUCHER_UNPOST: (id: string) => `/v1/vouchers/${id}/unpost`,
  VOUCHER_DUPLICATE: (id: string) => `/v1/vouchers/${id}/duplicate`,
  VOUCHER_DELETE: (id: string) => `/v1/vouchers/${id}`,
  VOUCHER_PDF: (id: string) => `/v1/vouchers/${id}/pdf`,
  VOUCHER_UNPAID: "/v1/vouchers/unpaid",
  VOUCHER_LAST_PRICE: "/v1/vouchers/last-price",
  CASH_VOUCHERS: "/v1/cash-vouchers",
  DEBT_SUMMARY: "/v1/debt/summary",
  DEBT_COLLECTIONS: "/v1/debt/collections",
  DEBT_COLLECTION_CREATE: "/v1/debt/collection",
  DEBT_COLLECTION_RESULT: (id: string) => `/v1/debt/collection/${id}/result`,
  DEBT_COLLECTION_CUSTOMERS: (id: string) => `/v1/debt/collection/${id}/customers`,
  DEBT_COLLECTION_CUSTOMER_DELETE: (id: string, detailId: string) => `/v1/debt/collection/${id}/customers/${detailId}`,
  AUDIT_LOGS: "/v1/audit-logs",
  AR_LEDGER: "/v1/ar-ledger",
  REPORTS_QUERY: "/v1/reports/query",
  REPORT_DEBT_NOTICE_EXCEL: "/v1/reports/debt-notice/excel",
  REPORT_TEMPLATES: "/v1/reports/templates",
  REPORT_FILTERS: "/v1/reports/filters",
  STOCK_CARD: "/v1/reports/stock-card",
  STOCK_CARD_EXCEL: "/v1/reports/stock-card/excel",
  PARTNER_DEBT_PDF: (partnerId: string) => `/v1/partners/${partnerId}/debt-pdf`,
  WAREHOUSES: "/v1/warehouses",
  WAREHOUSE_PRODUCTS: "/v1/warehouses/products",
  WAREHOUSE_BY_ID: (id: string) => `/v1/warehouses/${id}`,
  PRODUCTS: "/v1/products",
  PRODUCT_BY_ID: (id: string) => `/v1/products/${id}`,
  PRODUCT_IMPORT: "/v1/products/import",
  PRODUCT_IMPORT_VALIDATE: "/v1/products/validate",
  PRODUCT_IMPORT_COMMIT: "/v1/products/commit",
  PARTNERS: "/v1/partners",
  PARTNER_BY_ID: (id: string) => `/v1/partners/${id}`,
  PARTNER_IMPORT: "/v1/partners/import",
  PARTNER_IMPORT_VALIDATE: "/v1/partners/validate",
  PARTNER_IMPORT_COMMIT: "/v1/partners/commit",
  IMPORT_ANALYZE: "/v1/imports/analyze",
  IMPORT_VALIDATE: "/v1/imports/validate",
  IMPORT_COMMIT: "/v1/imports/commit",
  IMPORT_TEMPLATE: "/v1/imports/template",
  QUOTATIONS: "/v1/quotations",
  QUOTATION_BY_ID: (id: string) => `/v1/quotations/${id}`,
  QUOTATION_CONVERT_TO_SALES: (id: string) => `/v1/quotations/${id}/convert-to-sales`,
  USERS: "/v1/users",
  USER_BY_ID: (id: string) => `/v1/users/${id}`,
  USER_RESET_PASSWORD: (id: string) => `/v1/users/${id}/reset-password`,
  SYSTEM_SETTINGS: "/v1/system-settings",
  SYSTEM_ACCOUNTING_RESET: "/v1/system-settings/accounting-reset"
} as const;
