export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  MASTER_DATA: "/master-data",
  PURCHASE_VOUCHER: "/purchase",
  SALES_VOUCHER: "/sales",
  CASH_VOUCHERS: "/cash-vouchers",
  VOUCHER_FORM: "/vouchers/new",
  PRODUCTS: "/products",
  WAREHOUSES: "/warehouses",
  PARTNERS: "/partners",
  CUSTOMERS: "/partners?group=CUSTOMER",
  SUPPLIERS: "/partners?group=SUPPLIER",
  REPORTS: "/reports",
  VOUCHER_HISTORY: "/reports/voucher-history",
  AR_LEDGER_REPORT: "/reports/ar-ledger",
  STOCK_CARD_REPORT: "/reports/stock-card",
  SYSTEM: "/system",
  AUDIT_LOGS: "/audit-logs"
} as const;
